config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "beers/checkout" => "beers#checkout", :as => :checkout
  resources :beers
  root 'beers#index'
end

app/models/beer.rb
class Beer < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # allow additional user model parameters
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :untappd_id
    devise_parameter_sanitizer.for(:account_update) << [:untappd_id, :last_checkin]
  end
end

app/controllers/beers_controller.rb
require 'rest-client'
require 'json'
require 'cgi'

class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new
    @options = lookup( params[:q] )
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to beers_path, notice: 'Beer was successfully created.' }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to beers_path, notice: 'Beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /beers/checkout
  # fetch untappd checkins for each user and remove beers that have been
  # checked out
  def checkout
    @checkouts = Array.new
    User.all.each do |user|
      url = untappd_url('/user/checkins/' + user.untappd_id)
      if user.last_checkin.blank?
        user.last_checkin = "0"
      else
        url += "max_id=#{user.last_checkin}"
      end
      json_txt = RestClient.get(url)
      json_obj = JSON.parse(json_txt)
      user_checkouts = Array.new
      failed_checkouts = Array.new
      checkout_keyword = "#cellar"
      checkin_max = 0
      json_obj["response"]["checkins"]["items"].each do |checkin|
        checkin_id = checkin['checkin_id']
        checkin_max = checkin_id if checkin_id > checkin_max
        if checkin['checkin_comment'].include? checkout_keyword and checkin_id > user.last_checkin.to_i
          beer = Beer.find_by untappd: checkin['beer']['bid']
          if ( beer.nil? )
            failed_checkouts << checkin['beer']['beer_name']
          else
            beer.quantity = beer.quantity - 1
            beer.save
            user_checkouts << checkin['beer']['beer_name']
          end
        end
      end
      if checkin_max > user.last_checkin.to_i
        user.last_checkin = checkin_max
        user.save
      end
      @checkouts << { email: user.untappd_id,
                      user_checkouts: user_checkouts,
                      failed_checkouts: failed_checkouts }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:brewery, :location, :name, :style, :year, :quantity, :notes, :untappd)
    end

    def lookup( q )
      options = Array.new
      return options if q.blank?
      url = untappd_url('/search/beer') + "q=#{CGI.escape(q)}"
      json_txt = RestClient.get(url)
      json_obj = JSON.parse(json_txt)
      beers = json_obj["response"]["beers"]["items"]
      beers.each do |beer|
        brewery = beer['brewery']
        location = brewery['location']
        loc = brewery['country_name']
        loc += "--#{location['brewery_state']}" if loc == 'United States'
        loc += "--#{location['brewery_city']}"
        option = { id: beer["beer"]["bid"], name: beer["beer"]["beer_name"],
                   brewery: brewery['brewery_name'], location: loc,
                   style: beer["beer"]["beer_style"] }
        options << option
      end
      options
    end

    def untappd_url( path )
      return "http://api.untappd.com/v4#{path}?client_id=#{ENV['UNTAPPD_CLIENT_ID']}&client_secret=#{ENV['UNTAPPD_CLIENT_SECRET']}&"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brewery %><br>
    <%= f.text_field :brewery %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :style %><br>
    <%= f.text_field :style %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label :untappd %><br>
    <%= f.number_field :untappd %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/checkout.html.erb
<h1>Checkouts</h1>
<% @checkouts.each do |checkout| %>
  <p><%= checkout[:email] %></p>
  <ul>
    <% checkout[:user_checkouts].each do |user_checkout| %>
      <li><%= user_checkout %></li>
    <% end %>
    <% checkout[:failed_checkouts].each do |failed| %>
      <li>failed: <%= failed %></li>
    <% end %>
  </ul>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<h1>Listing beers</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Brewery</th>
      <th>Location</th>
      <th>Beer</th>
      <th>Style</th>
      <th>Year</th>
      <th>Qty</th>
      <th>Notes</th>
    </tr>
  </thead>

  <tbody>
    <% @beers.each do |beer| %>
      <tr>
        <td><%= link_to 'X', beer, method: :delete %></td>
        <td><%= beer.brewery %></td>
        <td><%= beer.location %></td>
        <td><%= link_to beer.name, edit_beer_path(beer) %></td>
        <td><%= beer.style %></td>
        <td><%= beer.year %></td>
        <td style="text-align: right;"><%= beer.quantity %></td>
        <td><%= beer.notes %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= form_tag('beers/new', method: 'get') do %>
  <%= text_field_tag 'q' %>
  <%= submit_tag 'Find Beer' %>
<% end %>
<p>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
  <%= link_to 'Profile',  edit_user_registration_path %>
</p>

app/views/beers/new.html.erb
<h1>New beer</h1>

<form>
<p>lookup: <input type="text" name="q"/> <input type="submit" value="lookup"/></p>
</form>

<% if params[:q].blank? %>
  <%= render 'form' %>
<% else %>
  <p>year, quantity</p>
  <% @options.each do |opt| %>
    <%= form_for(@beer) do |f| %>
      <%= f.hidden_field :brewery, value: opt[:brewery] %>
      <%= f.hidden_field :location, value: opt[:location] %>
      <%= f.hidden_field :name, value: opt[:name] %>
      <%= f.hidden_field :style, value: opt[:style] %>
      <%= f.hidden_field :untappd, value: opt[:id] %>
      <%= f.text_field :year, size: 5 %>
      <%= f.text_field :quantity, size: 3 %>
      <input type="submit" value="<%= opt[:name] %>"/>
    <% end %>
  <% end %>
<% end %>

<%= link_to 'View Cellar', beers_path %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brewery:</strong>
  <%= @beer.brewery %>
</p>

<p>
  <strong>Location:</strong>
  <%= @beer.location %>
</p>

<p>
  <strong>Name:</strong>
  <%= @beer.name %>
</p>

<p>
  <strong>Style:</strong>
  <%= @beer.style %>
</p>

<p>
  <strong>Year:</strong>
  <%= @beer.year %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @beer.quantity %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @beer.notes %>
</p>

<p>
  <strong>Untappd:</strong>
  <%= @beer.untappd %>
</p>

<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cellar</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>